address_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('',include('address_book.urls'))
]

address_book/urls.py
from django.urls import path, include
app_name = 'address_book'
from . import views
urlpatterns = [
    path('', views.index, name="index" ),
    path('add_address/', views.add_address, name="add-address"),
    path('show_addresses/', views.show_addresses, name="show-addresses"),
    path('<int:address_id>/update', views.update_address, name="update-address"),
    path('<int:address_id>/delete', views.delete_address, name="delete-address")
]

core/urls.py
from django.contrib.auth import logout
from django.urls import path
from django.contrib.auth.views import LoginView
from django.urls import path
from . import views
app_name = 'core'

urlpatterns = [
    path("login/", LoginView.as_view(), {"template_name": 'core/login.html' }, name="login"  ),
    path('register/', views.register, name="register"),
    path('logout/', views.logout_user, name="logout")

]

address_book/models.py
from django.db import models

# Create your models here.

core/models.py
from django.db import models
from django.contrib.auth.models import User
class Address(models.Model):
    date_added = models.DateTimeField(auto_now_add=True)
    address1 = models.CharField(max_length=255)
    address2 = models.CharField(max_length=255) 
    city = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=255)
    country_province = models.CharField(max_length=255)
    zip_code = models.IntegerField()
    country = models.TextField()
    details = models.TextField()
    owner = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.id

address_book/forms.py
from django import forms

from core.models import Address


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ['address1',
                  'address2',
                  'city',
                  'phone_number',
                  'country_province',
                  'zip_code',
                  'country',
                  'details' ]

address_book/views.py
from django.contrib.auth import login
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from .forms import AddressForm
from core.models import Address
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.
@login_required
def index(request):
    return render(request, "address_book/index.html")

@login_required
def add_address(request):
    if request.method != 'POST':
        form = AddressForm()
    else:
        form = AddressForm(data=request.POST)

        if form.is_valid():
            new_address = form.save(commit=False)
            new_address.owner = request.user
            new_address.save()
            return HttpResponseRedirect(reverse("address_book:show-addresses"))


    context = {"form": form}
    return render(request, 'address_book/add_address.html', context)

@login_required
def show_addresses(request):
    addresses = Address.objects.all()
    context = {'addresses': addresses}
    return render(request, 'address_book/show_addresses.html', context)

@login_required
def update_address(request, address_id):
    address = Address.objects.get(id=address_id)
    if request.method != "POST":
        form = AddressForm(instance=address)
    else:
        form = AddressForm(instance=address, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('address_book:show-addresses'))

    context = {'form': form, 'address':address}
    return render(request, 'address_book/update_address.html', context)

@login_required
def delete_address(request, address_id):
    address = Address.objects.get(id=address_id)
    address.delete()
    return HttpResponseRedirect(reverse('address_book:show-addresses'))

core/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib. auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse

def register(request):
    if request.method != "POST":
        form = UserCreationForm()
    else:
        form  = UserCreationForm(data = request.POST)

        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username = new_user.username, password=request.POST['password1'])
            login(request, authenticated_user)
            return  HttpResponseRedirect(reverse('address_book:show-addresses'))
    
    context = {'form': form}
    return render(request, 'core/register.html',context)


def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('core:login'))

core/templates/address_book/add_address.html
{% extends "address_book/index.html" %}

{% block main %}
    <div class="card col-md-6 p-lg-5 mx-auto">
         <h3>Add address</h3>
    <form method="POST" action="{% url 'address_book:add-address' %}">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-primary" name="submit">Save address</button>
    </form>
    </div>
{% endblock main %}

core/templates/address_book/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <title>Address Book</title>   

    <style>
            .address-book-options{
                display:none;
            }
    </style>
  
</head>
<body>
    <div class="container-fluid">
        {% block content %}
        
        {% endblock content %}
    </div>
</body>
</html>

core/templates/address_book/index.html
{% extends "address_book/base.html" %}

{% block content  %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{%  url 'address_book:index' %}">Address Book</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        </li>

     
      </ul>
        <a class="nav-link" href="{% url 'core:logout' %}">Logout</a>
    </div>
  </div>
</nav>
<main class="p-4">
  <ul class="d-flex" class="address-book-options">
        <li class="ms-5 btn"></li>
        <li class="ms-5 btn"></li>        
  </ul>
 
  {% block main %}
      
    <div class="col-md-8 p-lg-8 mx-auto my-5">
      <h1 class="display-5 fw-normal">lorem Ipsum</h1>
      <p class="lead fw-normal"> Welcome to Address Book, your online address store. </p>

      <a class="btn btn-outline-secondary"  href="{% url 'address_book:add-address' %}"> Add Address</a>
      <a class="btn btn-outline-secondary" href="{% url 'address_book:show-addresses'%}">Show address</a>

    </div>
    <div class="product-device shadow-sm d-none d-md-block"></div>
    <div class="product-device product-device-2 shadow-sm d-none d-md-block"></div>
  
  {% endblock main %}

<main>

{% endblock content %}

core/templates/address_book/show_addresses.html
{% extends "address_book/index.html" %}


{% block main %}

<div class="col-md-9 p-lg-8 mx-auto">
        <h2>Your Addresses</h2>
        <div class="address-container row">
              {% if addresses  %}
                          {% for address in addresses  %}
            <div class="card m-2" style="width: 18rem;">
              <div class="card-body">
                <h5 class="card-title">Address {{address.id}}</h5>
                <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
                <p class="card-text m-0">{{address.address1}}</p>
                <p class="card-text m-0">{{address.address2}}</p>
                <p class="card-text m-0">{{address.city}}</p>
                <p class="card-text m-0">{{address.phone_number}}</p>
                <p class="card-text m-0">{{address.country_province}}</p>
                <p class="card-text m-0">{{address.zip_code}}</p>
                <p class="card-text m-0">{{address.country}}</p>
                <p class="card-text m-0">{{address.details}}</p>
                <p class="card-text m-0">{{address.}}</p>
                <div class="card-actions my-2">
                  <a href="{% url 'address_book:update-address' address.id %}" class="btn btn-primary">Update</a>
                  <a href="{% url 'address_book:delete-address' address.id %}" class="btn btn-danger">delete</a>
                </div>
              </div>
            </div>  
            {% endfor %}
              {% else %}
                <div class="col-md-5 p-lg-5 mx-auto my-5">
                  <div class="text-center mx-auto "> <i style="font-size:5em" class="bi bi-box"></i></div>
                 <p>The current book is empty, add one address below</p>
                 <a class="text-center" href="/add_address">Add address</a>
                </div>
              {% endif %}
        </div>
</div>

{% endblock main %}

core/templates/address_book/update_address.html
{% extends "address_book/index.html" %}

{% block main %}
        <h3>Update address</h3>
        <form method="POST" action="{% url 'address_book:update-address' address.id %}" >
            {% csrf_token %}
            {{form.as_p}}
            <button class="btn btn-primary" name="submit">Update</button>
        </form>
{% endblock main %}

core/templates/core/register.html
{% extends "address_book/base.html" %}

{% block content %}
        <div class="card col-md-5 p-lg-5 mx-auto my-5">
            <h3>Register</h3>
    <form method="POST" action="" >
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-primary" name="submit" >Register</button>
    </form>
        </div>
{% endblock content %}